name: Deploy to Azure Functions

on:
  push:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Deploy to Azure Functions"
        uses: Azure/functions-action@v1
        with:
          app-name: YOUR_FUNCTION_APP_NAME
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
          package: api
