name: Deploy Backend

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository to github-repo
        uses: actions/checkout@v4
        with:
          path: github-repo

      - name: Deploy to glitch.com # best way so far to deploy to glitch.com; see https://help.glitch.com/hc/en-us/articles/16287554099213-Pushing-Local-Code-to-a-Project
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git clone ${{ secrets.BACKEND_GIT_URL }} glitch-repo
          cd glitch-repo
          cp -rf ${{ github.workspace }}/github-repo${{env.BACKEND_DIR }}/* .
          git add -A
          git commit -m "Automated deployed via GitHub Actions"
          git push ${{ secrets.BACKEND_GIT_URL }}
        env:
          BACKEND_DIR: /backend # the directory where the backend code is located
